// Generated by gencpp from file coorsa_interface/EvaluatePlanActionGoal.msg
// DO NOT EDIT!


#ifndef COORSA_INTERFACE_MESSAGE_EVALUATEPLANACTIONGOAL_H
#define COORSA_INTERFACE_MESSAGE_EVALUATEPLANACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <coorsa_interface/EvaluatePlanGoal.h>

namespace coorsa_interface
{
template <class ContainerAllocator>
struct EvaluatePlanActionGoal_
{
  typedef EvaluatePlanActionGoal_<ContainerAllocator> Type;

  EvaluatePlanActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  EvaluatePlanActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::coorsa_interface::EvaluatePlanGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct EvaluatePlanActionGoal_

typedef ::coorsa_interface::EvaluatePlanActionGoal_<std::allocator<void> > EvaluatePlanActionGoal;

typedef boost::shared_ptr< ::coorsa_interface::EvaluatePlanActionGoal > EvaluatePlanActionGoalPtr;
typedef boost::shared_ptr< ::coorsa_interface::EvaluatePlanActionGoal const> EvaluatePlanActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator1> & lhs, const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator1> & lhs, const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coorsa_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02a9914c5a239a844aceafa38ae90a79";
  }

  static const char* value(const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02a9914c5a239a84ULL;
  static const uint64_t static_value2 = 0x4aceafa38ae90a79ULL;
};

template<class ContainerAllocator>
struct DataType< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coorsa_interface/EvaluatePlanActionGoal";
  }

  static const char* value(const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"EvaluatePlanGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: coorsa_interface/EvaluatePlanGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"geometry_msgs/Pose[] box_poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvaluatePlanActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coorsa_interface::EvaluatePlanActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::coorsa_interface::EvaluatePlanGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORSA_INTERFACE_MESSAGE_EVALUATEPLANACTIONGOAL_H
