// Generated by gencpp from file coorsa_interface/PerformPickingGoal.msg
// DO NOT EDIT!


#ifndef COORSA_INTERFACE_MESSAGE_PERFORMPICKINGGOAL_H
#define COORSA_INTERFACE_MESSAGE_PERFORMPICKINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace coorsa_interface
{
template <class ContainerAllocator>
struct PerformPickingGoal_
{
  typedef PerformPickingGoal_<ContainerAllocator> Type;

  PerformPickingGoal_()
    : box_pose()  {
    }
  PerformPickingGoal_(const ContainerAllocator& _alloc)
    : box_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _box_pose_type;
  _box_pose_type box_pose;





  typedef boost::shared_ptr< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PerformPickingGoal_

typedef ::coorsa_interface::PerformPickingGoal_<std::allocator<void> > PerformPickingGoal;

typedef boost::shared_ptr< ::coorsa_interface::PerformPickingGoal > PerformPickingGoalPtr;
typedef boost::shared_ptr< ::coorsa_interface::PerformPickingGoal const> PerformPickingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator1> & lhs, const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator2> & rhs)
{
  return lhs.box_pose == rhs.box_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator1> & lhs, const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coorsa_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bdd5ee44b4a2c59f6264edb5e250b44";
  }

  static const char* value(const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bdd5ee44b4a2c59ULL;
  static const uint64_t static_value2 = 0xf6264edb5e250b44ULL;
};

template<class ContainerAllocator>
struct DataType< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coorsa_interface/PerformPickingGoal";
  }

  static const char* value(const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"geometry_msgs/Pose box_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PerformPickingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coorsa_interface::PerformPickingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coorsa_interface::PerformPickingGoal_<ContainerAllocator>& v)
  {
    s << indent << "box_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.box_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORSA_INTERFACE_MESSAGE_PERFORMPICKINGGOAL_H
